# Remove all 'included_files' lines related to models or assets.
# Netlify's build process handles the 'public' folder automatically.
# You only need to list files that are *outside* the normal build, like .env files.

[functions]
  included_files = [
    ".env",
    ".env.production",
    ".env.local",
    ".env.production.local"
  ]